### ISSUE TITLE
Issue with Find-GPOLocation in BloodHound.ps1

### ISSUE THREAD

**Issue by xfox64x** [BloodHoundAD/BloodHound#112]
First, went to your presentations at BlackHat/DEFCON, and they were awesome.

Second, I think I have found an issue with Find-GPOLocation in BloodHound.ps1 that may have already been mentioned somewhere and/or fixed, but I thought I would mention my fixes. Up front: I am using PowerShell 5.0.

**Affected lines**:
https://github.com/BloodHoundAD/BloodHound/blob/master/PowerShell/BloodHound.ps1#L3359-L3378

**Issue**: 
Generated two errors running Invoke-BloodHound (one while calling Get-NetOU, and the other calling Get-NetSite) where the conversion of GPOguid fails: "Cannot process argument transformation on parameter 'GUID'". Debugging, GPOguid appears to be a number of concatenated GPOguid's, instead of just one. Looking above these failed calls (to the affected lines mentioned above), it looks like the output of the Sort-Object block is being passed to the following ForEach-Object in a way that concatenates all fields of the matched "GPOGroup" objects, resulting in just one object being passed to the following ForEach-Object. Running Invoke-BloodHound with the Verbose flag confirms that the GPOname variable in the ForEach-Object loop comes out as all of the GPODisplayNames concatenated:
> GPOname: Test GPO 1 Test GPO 2 Test GPO 3 Test GPO 4  

When it should be doing:
> GPOname: Test GPO 1
> GPOname: Test GPO 2
> GPOname: Test GPO 3
> GPOname: Test GPO 4

**Fix**:
A quick fix would be to wrap the Sort-Object block in parenthesis:
>  (Sort-Object -Property GPOName -Unique -InputObject $(...)) | ForEach-Object ...

Though I do not feel qualified to criticize your work, I would also recommend changing the GroupMemberOf "if" (after the GroupSID "if" check) to an "elseif" (since it looks like you want unique objects and there is no further differentiation between the objects picked up by the separate "if" statements), incrementally storing operation results (like those returned from the Sort-Object) to make debugging easier and avoid the above issue, and clean up the formatting because I am a jerk   :P

I am not sure if this is just an issue with my environment or something dumb I am missing, but I think some structural changes will improve overall reliability, whatever. Thanks all for your hard work, you are all awesome, and let me know if I can help!

**Comment by bsaulsbury** [comment]
I am currently having the same issue. Because the call to Find-GPOLocation is used for local admin info, I believe this issue is preventing BloodHound from gathering local admin data for the machines in my domain. No local admin users or groups show up for my machines in Neo4j. 

I am new to BloodHound so I can't say if the issue was newly introduced or not. 

When I manually execute the Find-GPOLocation function, I get the same issue as xfox64x:

```
PS C:\Users\[redacted]\Downloads\BloodHound-win32-x64> Find-GPOLocation -Domain [redacted] -DomainController [redacted]
Get-NetOU : Cannot process argument transformation on parameter 'GUID'. Cannot convert value to type System.String.
At C:\Users\[redacted]\Downloads\BloodHound-win32-x64\BloodHound.ps1:3404 char:77
+ ... in $Domain -DomainController $DomainController -GUID $GPOguid -FullDa ...
+                                                          ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-NetOU], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-NetOU
 
Get-NetSite : Cannot process argument transformation on parameter 'GUID'. Cannot convert value to type System.String.
At C:\Users\[redacted]\Downloads\BloodHound-win32-x64\BloodHound.ps1:3452 char:79
+ ... in $Domain -DomainController $DomainController -GUID $GPOguid -PageSi ...
+                                                          ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-NetSite], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-NetSite
 

PS C:\Users\[redacted]\Downloads\BloodHound-win32-x64>
```

**Comment by rvazarkar** [comment]
Can either of you hop on the Bloodhound slack channel and talk to me directly so I can try and figure out how to debug this?

**Comment by rvazarkar** [comment]
The new ingestor has been released at https://github.com/BloodHoundAD/SharpHound/releases.

If you could try the same collection there and let me know if it works, that would be great!

**Comment by bsaulsbury** [comment]
Rohan,

As it turns out, our domain uses GPO Preferences to populate our local 
Administrator groups rather than Restricted Groups. It looks like the 
code to parse out Group Policy Preference files isn't implemented in 
SharpHound yet.

 From reading Will's blog post here 
<http://www.harmj0y.net/blog/redteaming/where-my-admins-at-gpo-edition/>, 
I saw that there's a partial PowerShell implementation in PowerView 
<https://github.com/PowerShellMafia/PowerSploit/blob/dev/Recon/PowerView.ps1>.

I wrote some C# code in SharpHound to gather the data for my 
environment, but my code doesn't take any filtering into account, which 
is Will's major headache according to his comments in PowerView lol.

I was going to try to write some basic filtering logic based on the code 
in PowerView, but I got sidetracked with some other stuff for work + 
studying for my upcoming OSCP exam. The code that I've written so far 
works in my environment, but I haven't tested it anywhere else. My code 
is pretty sloppy, but if you're planning on adding GPO Preferences 
support to SharpHound in the near future, I could send it to you to use 
as a jumping off point if you're interested.

--Brendan

**Comment by xfox64x** [comment]
I'll give it a go, at some point, though I've made such heavy modifications to the previous ingestor that I don't even know who I am, anymore.

**Comment by rvazarkar** [comment]
So it turns out, I actually missed some code when porting to SharpHound, so thats why the group policy stuff isn't working. I'll work on porting the missing code over soon. Sorry about that!

**Comment by rvazarkar** [comment]
Should be fixed!
