### ISSUE TITLE
False positive on HasSession

### ISSUE THREAD

**Issue by redbirdjr** [BloodHoundAD/BloodHound#118]
I believe I'm getting a false positive and wondering if it's user error on my part. I've run Invoke-Bloodhound from a Windows7 PC using a local admin account (no special domain creds). The PC is PC-01. The results show that AdminJoe has a session to my machine, suggesting I could dump his creds and then move laterally. I can find no way he would have a session. I've freshly rebooted, I've checked services and scheduled tasks for anything running under his account. I've searched the registry and hard drive for any sign of his name. There's nothing for him under HKU or C:\Users. I've run PowerView: GetNetSession and GetNetLoggedOn as well as the SysInternals PSLoggedOn. I just can't find any sign of this user and I'm trying to figure out where he may be coming from.
![hassession](https://user-images.githubusercontent.com/31355017/29726129-a42b9c3e-899c-11e7-8739-3e7931647d36.jpg)

**Comment by jbfuzier** [comment]
I also had a similar issue on my testing.

**Comment by jbfuzier** [comment]
May be related to https://github.com/BloodHoundAD/BloodHound/issues/93

**Comment by redbirdjr** [comment]
I don't believe it's related, in that in my case there is no local account for AdminJoe. If I understand 93 properly, it would be a case where there's a session for a local AdminJoe and Bloodhound makes it look like a domain AdminJoe. We have been discussing on the Slack channel. Since BH uses Get-NetSession to gather session info, maybe it could be adjusted to capture the ComputerName reporting the session, since I'm told it's possible another system may be reporting they have a session to PC-01 when they don't.

**Comment by rvazarkar** [comment]
FWIW, we just parse the results from NetSessionEnum. Whatever you're seeing is related to that. The only thing I can think of is if PTR records are screwed up in the environment, because that's whats used to resolve the IPs back to a computer name. Its possible that a PTR points to a wrong hostname, and that's whats causing this issue.

We've resolve the 127.0.0.1 and [::1] issue in the new ingestor, so hopefully that shouldn't be a problem.

I'll leave this open, but if you can narrow down whats causing it in the code, or if its actually an issue, then let me know. For reference, the corresponding ingestor code is here:

https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Enumeration/SessionHelpers.cs#L88
