### ISSUE TITLE
Getting started issue 

### ISSUE THREAD

**Issue by adrastee** [BloodHoundAD/BloodHound#136]
Hi,
Following Getting Started on Windows I am stuck at :

"5. Authenticate to the provided sample graph database at bolt://localhost:7687. The username is "neo4j", and the password is "BloodHound"."

"Login" button is disabled. No errors raised.
Screen : https://img4.hostingpics.net/pics/566923Capture.png

What can I do ?

Thanks.

**Comment by dp001** [comment]
Hi,

You need to point Neo4j to  the BloodHound DB folder

The a test DB is included in the Git source

Sent from iDavid

On 25 Oct 2017, at 10:12, adrastee <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
Following Getting Started on Windows I am stuck at :

"5. Authenticate to the provided sample graph database at bolt://localhost:7687. The username is "neo4j", and the password is "BloodHound"."

"Login" button is disabled. No errors raised.
Screen : https://img4.hostingpics.net/pics/566923Capture.png

What can I do ?

Thanks.

**Comment by adrastee** [comment]
> You need to point Neo4j to the BloodHound DB folder

How?

**Comment by dp001** [comment]
Download the BloodHound source code from Git

It contains the BloodHoundExampleDB.graphdb folder
Copy everything in it to C:\Users\<username>\Documents\Neo4j\default.graphdb

Start Neo4j

Otherwise, on the Neo4j application, click “Choose” and select the folder where you extracted the BloodHoundExampleDB.graphdb one

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JED1SEN7INEL** [comment]
If after performing the steps by dp001 above, you are still unable to click login button, try closing bloodhound.exe and then launching bloodhound.exe as an administrator. This was my problem and solution when I was experiencing what you are describing.
