### ISSUE TITLE
BloodHound Boots To a Blank Screen

### ISSUE THREAD

**Issue by Adamtimtim** [BloodHoundAD/BloodHound#173]
I setup neo4j on Kali without any issues, however when I run BloodHound I get the following blank screen with no information. 

![image](https://user-images.githubusercontent.com/18688989/39238687-ce99472a-4876-11e8-8e4c-a5e549f42b32.png)

Is there anyway to run it in debug mode to see any errors?

**Comment by aconite33** [comment]
Control+R (Forces it to refresh)

Thanks to mr64Bit in the Slack channel.

**Comment by rvazarkar** [comment]
Closing this issue for now

**Comment by aeleuterio** [comment]
Hi I am facing the same issue and Ctrl+R does not solve it for me. I tried running the distribution through `apt get` and also built both prod and dev servers locally. They all had the same result. After pressing Ctrl+R I get two new `[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.` on the console but the window does not reload and remains blank.
I'm running Bloodhound on Kali with Parallels VM.

Thank you! cc @rvazarkar

**Comment by Mefist0** [comment]
I have the same issue as @aeleuterio 
I tried it on different systems: Kali VM (VMWare) and on the real hardware - always the same situation.
Bloodhound version is 3.0.3
Neo4j version is 3.5.3

**Comment by Evedel** [comment]
Same problem
Kali on VirtualBox
Bloodhound: 3.0.5
neo4j: 4.0.7

**Comment by thomasncc** [comment]
I am hitting the same issue. 
- W10 VM
- Bloodhound - 4.0.3
- neo4j - 4.4.3

**Comment by CacheMoneyPlaya** [comment]
If you're compiling the Bloodhound application yourself, make sure that you run the client server first with `npm run start:server` then run `npm run start`
