### ISSUE TITLE
Bloodhound doesn't load - white screen

### ISSUE THREAD

**Issue by variableresults** [BloodHoundAD/BloodHound#221]
I installed the latest release from scratch, including Neo4j, following the Wiki instructions, and when running Bloodhound I don't get a login prompt. All I get is a blank white screen. This is on every version since 2.0 was released on Server 2012 R2. What is missing?

Versions prior to 2.0 work fine.

**Comment by Raknor** [comment]
Same issue.
When stating bloodhound, in neo4j, I have the following log:
"The client is unauthorized due to authentication failure."

It's been some time since I used bloodhound. So I dunno what could be the credentials.

However, although I can reconfigure neo4j, I found no way to reconfigure bloodhound.

The binary has no help menu. No configuration file...

I've already reinstalled bloodhound, but still the problem.

**Comment by rvazarkar** [comment]
Hit Ctrl + R to reload the UI
