### ISSUE TITLE
Graph Display/Query Performance in Large Corporate Environments

### ISSUE THREAD

**Issue by johnmccash** [BloodHoundAD/BloodHound#276]
I've got a database that's sized as follows:
Users: 78827
Computers: 58478
Groups: 116385
Sessions: 33703
ACLs: 3579030
Relationships: 6257100
The current build works OK (Thanks for fixing that Timeout!), but, for example, the 'Find Shortest Paths to Domain Admins' query takes dozens of minutes to load. During this time, I see typically one or two Bloodhound & java processes using about 3% of my 32 CPUs (actually it's a 16 core with hyperthreading). I've already cranked the memory parameters for both neo4j and java way up (I've got 64GB).  Is there something that could be multithreaded that currently isn't?

**Comment by rvazarkar** [comment]
Unfortunately, the answer is no. 

Just to give you an idea, the query process looks something like this.

First, we ask Neo4j for data. Depending on what you're asking for this can take quite a bit of time, since, for example, Shortest Paths to Domain Admins is an unbounded shortest path query from every node in the database. In your scenario, Neo4j is trying to figure out shortest path between ~250k nodes. There's not way to optimize this past what we have.

Next, Neo4j feeds the data to the BloodHound UI. There's no way to multithread this either, as we're getting a stream of data. This takes a bunch of time too if you're doing a huge query.

After we get all the data, we drop the data into a child process which processes the data to hide nodes and improve graph performance. Maybe this process could be optimized a bit, but the logic is pretty straightforward so I doubt it.

Once processing is complete, the child process sends the final data back up to the UI, which then attempts to render the graph. Rendering the initial graph is easy, but doing layouts gets exponentially harder the more nodes there are on the graph. 

If you look at the lifecycle of a query, there's really not that much leeway for optimization. The reality is we're just asking for too much data.

**Comment by johnmccash** [comment]
Interesting... Any way to benchmark which piece of this is taking how much time? For example, I'm wondering whether the lion's share of the delay is actually in Neo4j, Bloodhound, or data transfer between the two. It looks to me like whatever is happening is single threaded, which seems a little odd to me. I'd be fine if it was just maxing out all the processors, but it's definitely not. The simplest explanation for this is probably that it's data transfer, but that feels wrong to me somehow. I've got dbms.threads.worker_count=32 in my neo4j config, so I'd think if it was the query, I'd be seeing at least some multithreaded CPU usage. Maybe I'm being naive about my expectations for Neo4j's multithreading performance?

**Comment by variableresults** [comment]
I'm also in a very large domain and Bloodhound has similar issues. What I'm wondering is this: if the code can't be optimized any further, can you speak on whether these queries are IOPS bound, CPU bound, RAM bound, or some combination of those three? That could at least allow us to more effectively throw hardware at the performance problems.

**Comment by rvazarkar** [comment]
To answer this question very late, I don't know how much more resources will help. The problem is just the complexity of the calculations for node placement.  You could try throwing more CPU at the problem, but since everything is operating on a single thread I doubt it'll help much.
