### ISSUE TITLE
Everything is white

### ISSUE THREAD

**Issue by amra13579** [BloodHoundAD/BloodHound#490]
Using kali linux arm64 version on an M1 macbook with UTM, whenever I try to launch BloodHound the entire screen is just plain white. CTRL + R doesn't fix the problem and CTRL+SHIFT+i doesn't show the console. The interesting part is that the UI is there and so is the console, meaning that the cursor does change it's shape to input text when hovering above the credentials window, and I am able to right click on the console after I activate it, but all I see is just white. I have tried both the precomiled binaries and building from source nothing worked. Any solution to this? or at least a way to see some error logs to check what's going wrong?

**Comment by JliCH** [comment]
@amra13579 I have the same issue too. 
The issue may be caused by the setting "Emulated Display Card" in Display tab. Try to use  "virtue-ramfb" instead of "virtue-ramfb-gl".

**Comment by tecxx** [comment]
we had the same issue recently and it was caused by a missing "bundle.js" file:

![image](https://user-images.githubusercontent.com/4305825/148229113-b971b5e1-82ab-48c9-8259-831828e4e640.png)


not sure if this was removed by an aggressive AV or an error while unzipping or something else. we compared the "fresh" unzip with an old install and found this file missing.

**Comment by amra13579** [comment]
Using the latest Kali update which improved compatibility with the VMware tech preview, seems to have fixed the issue, everything works as expected now.
