### ISSUE TITLE
Missing Objects - Data collected by AzureHound

### ISSUE THREAD

**Issue by phl0x1** [BloodHoundAD/BloodHound#499]
I ran AzureHound for the first time in my environment and experienced some things iam wondering about.
I do have collected for about 14 hours and imported the data in BloodHound.
What I’ve seen is, that the DB stats are showing different numbers as we actually have in AD.
        regarding Users we do have ~ 200000 in Azure (counted with (Get-AzADUser ).count) and BloodHound shows us only 51525.
        regarding Groups we do have 10000 in Azure (counted with (Get-AzADGroup).count) and BloodHound shows us only 64648
        regarding Service Principals we do have 2000 in Azure (counted with Get-AzureADServicePrincipal -all $true).count) and BloodHound shows us only 2
        regarding the Devices, the numbers are pretty much the same, so this works for me
 2. I haven’t found some Enterprise Apps like the Office 365 Exchange Online or “AirWatch by VMWare”. If I try to find them via Get-AzureADServicePrincipal I could find them.
     I guess the reason for this is Line 1359 in AzureHound, where you first looking fore Get-AzADApplication (which isn’t finding this apps mentioned above) and then piping into Get-AzADServicePrincipal.

**Comment by yellow-starburst** [comment]
This is normal.
Azure ad will accumulate more users and groups compared to active directory.
Can you please close?

**Comment by ddlees** [comment]
@phl0x1 Is it possible that you are syncing onPrem entities into Azure AD using [Azure AD Connect](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/whatis-azure-ad-connect)?

AFAIK the powershell commands do not distinguish between the cloud and onprem entities; whereas AzureHound/BloodHound makes this distinction via the `OnPremisesSecurityIdentifier` attribute. This *could* be what you are seeing for AzUsers and AzGroups.

(See https://github.com/BloodHoundAD/BloodHound/blob/master/Collectors/AzureHound.ps1#L147)

Regarding the AzADApplication -> AzADServicePrincipal enumeration you are correct, `Get-AzADApplication` only returns applications that belong to that tenant including those that do not have an associated service principal. In contrast, `Get-AzADServicePrincipal -all $true` returns service principals that for that tenant including those principals that map to applications in other tenants. So you're probably only seeing 2 because AzureHound is enumerating only the apps belonging to that tenant that actually have an associated service principal.
