### ISSUE TITLE
EXE & PowerShell collectors issues

### ISSUE THREAD

**Issue by init5-SF** [BloodHoundAD/BloodHound#596]
Downloaded and tested the latest PowerShell collector, it doesn't seem to work for some reason.

```
PS C:\Users\Administrator\Desktop> Invoke-BloodHound -CollectionMethod all
Exception calling "Invoke" with "2" argument(s): "Method not found: '!!0[] System.Array.Empty()'."
At C:\Users\Administrator\Desktop\hound.ps1:642 char:88
+ ... nvoke($Null, @(,$passed))
+                    ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : MissingMethodException
```

Tested again with the EXE collector and got this:
```
PS C:\Users\Administrator\Desktop> .\SharpHound.exe -c all

Unhandled Exception: System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Sharphound.Program.<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sharphound.Program.<Main>(String[] args)
```

Test machines is Windows Server 2012 R2 & Microsoft Windows Server 2019 Datacenter, both fully updated.

**Comment by MrHoz** [comment]
I have same exact issue on a Windows Server 2012 R2.

**Comment by rvazarkar** [comment]
Will look into this

**Comment by JonasBK** [comment]
Is this still an issue with the new sharphound v1.1.1?

**Comment by ramus82** [comment]
yes, the issue is still there

```
> PS C:\Users\user\Documents> .\SharpHound.ps1                                             
> Exception calling "Invoke" with "2" argument(s): "Method not found: '!!0[] System.Array.Empty()'."        
> At C:\Users\user\Documents\SharpHound.ps1:416 char:91 
> + ... nvoke($Null, @(,$passed))                                                                           
> +                    ~~~~~~~~                                                                             
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException                             
>     + FullyQualifiedErrorId : MissingMethodException           
```

**Comment by wwwGeneral** [comment]
Issue still here, can't run SharpHound (exe or ps1) in old systems since a few versions.
We need another version of SharpHound for older Windows version (Windows 7, Windows Server 2008 R2 for example) that don't require the installation of newer frameworks.

In my case SharpHound from 3.0.5 version was working fine on those old systems but I couldn't load the files in the lastest BloodHound (compatibility problems).

I will be glad someone does it

**Comment by Anon-Exploiter** [comment]
Ran into the same issue, it seems its because of .Net version installed on the victim machine - v4.6 should fix this: 
https://stackoverflow.com/questions/31253747/method-not-found-0-system-array-empty 

Victim's machine:
![image](https://github.com/BloodHoundAD/BloodHound/assets/18597330/6545e434-a954-4c08-9571-90f0b0c8977a)

One idea is to try older versions of SharpHound which were written according to v4.0 or less.
