### ISSUE TITLE
Issue of white page when clicking help page

### ISSUE THREAD

**Issue by rea1-name-h1dden** [BloodHoundAD/BloodHound#635]
Hi good people,

When I right-click a relationship between two nodes to go "help" to view further exploit info, this "white page" pop up and I can't do anything except exit the program or 'ctrl+R' refresh the page. But I could never ever view the help info. 

Furthermore, I also checked other AD JSON data, and it turned out that there is always some help page triggering the white page such as the help info of the "GenericWrite" relationship.

I am using neo4j 5.2.0, bloodhound 4.2.0, java 17.0.5 and arm64 Kali VM.

I would be very grateful if anyone could give me a little help.

![Screen Shot 2023-01-09 at 6 09 05 pm](https://user-images.githubusercontent.com/84689923/211420640-a3404c3f-994d-458f-853a-6c36b4bdd7f7.png)

**Comment by DimitriDokuchaev** [comment]
I want to add that i have the same exact problem as reported above.
The above happens when i want to check the help for generic write over a GPO

neo4j - 5.4.0
java Version - openjdk 19.0.1 2022-10-18
bloodhound - 4.2.0
OS - Ubuntu 22.04 LTS x86_64


![BloodhoundError](https://user-images.githubusercontent.com/5759671/218491425-3aa853cb-f4d9-496c-a1df-f617a3f6045b.png)

**Comment by JonasBK** [comment]
Duplicate of https://github.com/BloodHoundAD/BloodHound/issues/589
